# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-ecs-cloudwatch-autoscaling
  description: Terraform module to autoscale ECS Service based on CloudWatch metrics
  homepage: https://cloudposse.com/accelerate
  topics: autoscaling, autoscaler, autoscale, ecs, ecs-cluster, ecs-service, cloudwatch, hcl2


